### ISSUE TITLE
How to perform mutations

### ISSUE THREAD

**Issue by SaileshKumar** [skyhookadventure/appsync-client#15]
Hi!

I'm trying to use your library, but was wondering how to use it for mutations instead of queries. 

Is it something like:
```
client.request({
  query: mutationName
  variables: {
    input: {
      id: "test
    }
  }
});
```

In case it matters, I'm using AWS Amplify.

**Comment by chrisharrison** [comment]
Mutations are queries.

**Comment by alan-cooney** [comment]
As chrisharrison says you can just put the full mutation in the query field (not just the mutation name) because under the hood all mutations are just queries of type Mutation
