### ISSUE TITLE
httpsRequestPromisified truncates large responses

### ISSUE THREAD

**Issue by tombuckley91** [skyhookadventure/appsync-client#4]
The current https implementation registers ```result.on("data")``` and then either resolves or rejects the enclosing promise. In the case of large 'results', it is expected that the "data" event will be emitted multiple times. Instead, we need to register the ```result.on("end")``` event listener and handle our ```JSONification``` and promise resolution here. This will ensure we have received all of the data before returning.

Thank you,
Tom

**Comment by tombuckley91** [comment]
I have a PR for this but I'll await your feedback on the existing PR first.

**Comment by alan-cooney** [comment]
Should be resolved now @tombuckley91 - thanks for reporting this
